spring:
  jpa:
    hibernate:
      ddl-auto: update    # dev: tự update schema
    show-sql: true

  liquibase:
    enabled: false        # dev: dùng ddl-auto thay Liquibase

logging:
  level:
    com.instagram: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
