spring:
  jpa:
    hibernate:
      ddl-auto: update    # dev: tự update schema
    show-sql: true

  liquibase:
    enabled: false        # dev: dùng ddl-auto thay Liquibase

# MinIO local
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

logging:
  level:
    com.instagram: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
